// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	scraper "romsRename/internal/scraper"

	mock "github.com/stretchr/testify/mock"
)

// Scraper is an autogenerated mock type for the Scraper type
type Scraper struct {
	mock.Mock
}

// CanSearchByHash provides a mock function with no fields
func (_m *Scraper) CanSearchByHash() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanSearchByHash")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CanSearchByName provides a mock function with no fields
func (_m *Scraper) CanSearchByName() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanSearchByName")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Name provides a mock function with no fields
func (_m *Scraper) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SearchByHash provides a mock function with given fields: ctx, query
func (_m *Scraper) SearchByHash(ctx context.Context, query scraper.SearchQuery) (*scraper.Metadata, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchByHash")
	}

	var r0 *scraper.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, scraper.SearchQuery) (*scraper.Metadata, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, scraper.SearchQuery) *scraper.Metadata); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scraper.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, scraper.SearchQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByName provides a mock function with given fields: ctx, query
func (_m *Scraper) SearchByName(ctx context.Context, query scraper.SearchQuery) (*scraper.Metadata, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 *scraper.Metadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, scraper.SearchQuery) (*scraper.Metadata, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, scraper.SearchQuery) *scraper.Metadata); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*scraper.Metadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, scraper.SearchQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScraper creates a new instance of Scraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scraper {
	mock := &Scraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
