// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRenaming(arg1) {
  return window['go']['main']['App']['ApplyRenaming'](arg1);
}

export function CheckPreviousSession(arg1) {
  return window['go']['main']['App']['CheckPreviousSession'](arg1);
}

export function GetAPICredentials(arg1) {
  return window['go']['main']['App']['GetAPICredentials'](arg1);
}

export function GetConfigValue(arg1, arg2) {
  return window['go']['main']['App']['GetConfigValue'](arg1, arg2);
}

export function PauseScraping() {
  return window['go']['main']['App']['PauseScraping']();
}

export function ResumeScraping() {
  return window['go']['main']['App']['ResumeScraping']();
}

export function SaveAPICredentials(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveAPICredentials'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveConfigValue(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigValue'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartScraping(arg1, arg2) {
  return window['go']['main']['App']['StartScraping'](arg1, arg2);
}

export function StopScraping() {
  return window['go']['main']['App']['StopScraping']();
}
