// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function ApplyRenaming(arg1:Array<number>):Promise<Array<main.ErrorResult>>;

export function CheckPreviousSession(arg1:string):Promise<main.SessionInfo>;

export function GetAPICredentials(arg1:string):Promise<db.APICredentials>;

export function GetConfigValue(arg1:string,arg2:string):Promise<string>;

export function PauseScraping():Promise<void>;

export function ResumeScraping():Promise<void>;

export function SaveAPICredentials(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:boolean,arg8:boolean):Promise<void>;

export function SaveConfigValue(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartScraping(arg1:string,arg2:boolean):Promise<void>;

export function StopScraping():Promise<void>;
